### PR TITLE
Add Docstring linter

### PR DESCRIPTION
**Pull request by jacobbieker**
# Pull Request

## Description

This adds a check and pre-commit hook for Google formatted dosctrings. 

## How Has This Been Tested?

This PR should test nowcasting_utils on every push

- [ ] No
- [x] Yes

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/nowcasting/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by JackKelly** [comment]
Awesome!  Forgive my naivete but is there any way to have this setup for all our Python repos in one go?  I guess assume not?!

**Comment by peterdudfield** [comment]
Well this is hugely useful - https://github.com/openclimatefix/nowcasting_utils/runs/3622549429

Do you think its worth sorting these before merging?

**Comment by jacobbieker** [comment]
> Awesome! Forgive my naivete but is there any way to have this setup for all our Python repos in one go? I guess assume not?!

Unfortunately it doesn't seem like it. The .github repo only syncs templates and Contributer.md/funding.md and those kinds of files. There does not seem to be a way to sync workflow and GitHub Actions across all of them.

**Comment by peterdudfield** [comment]
> > Awesome! Forgive my naivete but is there any way to have this setup for all our Python repos in one go? I guess assume not?!
> 
> Unfortunately it doesn't seem like it. The .github repo only syncs templates and Contributer.md/funding.md and those kinds of files. There does not seem to be a way to sync workflow and GitHub Actions across all of them.

We can make a meta-repo  (another one) and then when you start a repo you can copy from this blank one. 
Perhaps we havent got to many, so we can just copy them over

**Comment by jacobbieker** [comment]
> Well this is hugely useful - https://github.com/openclimatefix/nowcasting_utils/runs/3622549429
> 
> Do you think its worth sorting these before merging? I'd happily help. One person start from the bottom, one person start from the top

Possibly, yeah, so then its passing the tests. Maybe we split it? I can write ones for the stuff from SatFlow, and you write the ones from predict_pv_yield?

**Comment by JackKelly** [comment]
On the topic of whether we should turn off all the warnings about whitespace... I know it's painful now, and really tedious, but I'd vote for keeping most of (all of?!?) the whitespace warnings.  (I've just skimread the list of warnings and they seem vaguely sane).  And maybe we can review after a few days to see if it's hurting productivity?!?  Hopefully, whilst it's painful right now, we should get into the swing of things fairly soon?!

**Comment by jacobbieker** [comment]
> On the topic of whether we should turn off all the warnings about whitespace... I know it's painful now, and really tedious, but I'd vote for keeping most of (all of?!?) the whitespace warnings. I've just skimread the list of warnings and they seem vaguely sane. And maybe we can review after a few days to see if it's hurting productivity?!? Hopefully, whilst it's painful right now, we should get into the swing of things fairly soon?!

Yeah, I'd probably agree. Its just going to be painful, especially on ones with a lot more code than this one. This one being fairly small is the reason I tried it here first to see how many there would be.

**Comment by jacobbieker** [comment]
> > On the topic of whether we should turn off all the warnings about whitespace... I know it's painful now, and really tedious, but I'd vote for keeping most of (all of?!?) the whitespace warnings. I've just skimread the list of warnings and they seem vaguely sane. And maybe we can review after a few days to see if it's hurting productivity?!? Hopefully, whilst it's painful right now, we should get into the swing of things fairly soon?!
> 
> Yeah, I'd probably agree. Its just going to be painful, especially on ones with a lot more code than this one. This one being fairly small is the reason I tried it here first to see how many there would be.

But once its fixed, it should be a lot better going forward, and makes the code a lot more uniform and readable I think

**Comment by JackKelly** [comment]
Modifying the docstrings to pass the linter's requirements could make a great "first issue" for people who are new to the codebase :)  (not very sexy work, though!)...  I'll add issues to the repos and mark them "great first issue"

**Review by peterdudfield — APPROVED** [review]

**Pull request merged**
